language: node_js
node_js:
  - "6.10.0"
install:
  - npm install
script:
  - npm run build
after_success:
  - bash ./scripts/deploy.sh
deploy:
  provider: surge
  project: public
  domain: https://realease.surge.sh
  skip_cleanup: true
