sudo: false
language: node_js
node_js:
  - lts/*

script:
  - npm run build
before_deploy:
  - bash ./scripts/deploy.sh
cache:
  directories:
    - ./node_modules/
deploy:
  provider: surge
  project: ./public/
  skip_cleanup: true
